### ISSUE TITLE
Python implementations of some functionalities

### ISSUE THREAD

**Issue by janash** [lengxupa/polymerxtal#2]
One nice thing about python is that many functionalities are implemented already. Please consider the following:

1. Use numpy arrays instead of a self-written vector class.
1. Use python `random` module instead of your own random number generator - https://docs.python.org/3/library/random.html . The random module in python uses the same random number generator as your rng implementation (Mersenne Twister)

**Comment by lengxupa** [comment]
Thank you, Jessica! I have removed vector and rng module in polymermodeler.
