### ISSUE TITLE
Python and destructors

### ISSUE THREAD

**Issue by janash** [lengxupa/polymerxtal#3]
I think you do not need the destructors (`__del__`) in most of your classes. I understand that this is a translation of C code, but Python does a lot more memory cleaning/clearing for you than C. In most cases, these `__del__` destructors are unnecessary. I would recommend not rewriting ones you have left to translate, and also would recommend getting rid of the ones you have.

**Comment by lengxupa** [comment]
Thank you, Jessica! You are right. I have removed all destructors (__del__) in polymermodeler module.
